// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bibzeducbhsxlelgpxrc.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpYnplZHVjYmhzeGxlbGdweHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDg2MjY1NzcsImV4cCI6MjAyNDIwMjU3N30.YB_HHH3W3_GlDff1EBBpRtqvyGr-tsG0Q8UXxeJfwBY";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    db: {
      schema: 'public'
    }
  }
);